apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: leaderselection-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leaderselection-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leaderselection-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leaderselection-role
subjects:
  - kind: ServiceAccount
    name: leaderelection-sa